{{- if .Values.ingress.enabled -}}
{{- $fullName := include "app.fullname" . -}}
{{- $ingressPath := .Values.ingress.path -}}
{{- $cluster := default "live" .Values.ingress.cluster -}}
{{- $clusterColour := ternary "green" "blue" (eq $cluster "live") -}}
{{- $awsWeight := default "100" .Values.ingress.aws_weight -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ print $fullName "-new" }}
  labels:
    app: {{ template "app.name" . }}
    chart: {{ template "app.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  annotations:
    {{ if .Values.ingress.enable_whitelist }}nginx.ingress.kubernetes.io/whitelist-source-range: {{ include "app.joinListWithComma" .Values.whitelist | quote }}{{ end }}
    nginx.ingress.kubernetes.io/custom-http-errors: "418"
    external-dns.alpha.kubernetes.io/set-identifier: {{ print $fullName "-new-" .Release.Namespace "-" $clusterColour }}
    external-dns.alpha.kubernetes.io/aws-weight: {{ $awsWeight | quote }}
spec:
  ingressClassName: default
  tls:
  {{- range .Values.ingress.hosts }}
  - hosts:
    - {{ .host }}
    {{ if .cert_secret }}secretName: {{ .cert_secret }}{{ end }}
  {{- end }}
  rules:
  {{- range .Values.ingress.hosts }}
    - host: {{ .host }}
      http:
        paths:
          - path: {{ $ingressPath }}
            backend:
              serviceName: {{ $fullName }}
              servicePort: http
  {{- end }}
{{- end }}
