apiVersion: v1
kind: Secret
metadata:
  name: {{ template "app.name" . }}
type: Opaque
data:
  BASM_BUCKET_NAME: {{ .Values.secrets.BASM_BUCKET_NAME | b64enc | quote }}
  BASM_AWS_ACCESS_KEY_ID: {{ .Values.secrets.BASM_AWS_ACCESS_KEY_ID | b64enc | quote }}
  BASM_AWS_SECRET_ACCESS_KEY: {{ .Values.secrets.BASM_AWS_SECRET_ACCESS_KEY | b64enc | quote }}
  SPREADSHEET_PASSWORD: {{ .Values.secrets.SPREADSHEET_PASSWORD | b64enc | quote }}
