spring:
  application:
    name: calculate-journey-variable-payments
  jpa:
    show-sql: true
    generate-ddl: false
    properties:
      hibernate.jdbc.batch_size: 5
    hibernate:
      ddl-auto: none
      order_inserts: true
      order_updates: true
      batch_versioned_data: true
      generate_statistics: true

  datasource:
    url: ${APP_DB_URL}
    hikari:
      pool-name: LIP-DB-CP
      maximum-pool-size: 20
      max-lifetime: 600000
      connection-timeout: 1000
      validation-timeout: 500

  session:
    store-type: jdbc
    jdbc:
      initialize-schema: never
    timeout: 20M
  security:
    oauth2:
      client:
        provider:
          hmpps:
            authorization-uri: ${HMPPS_AUTH_BASE_URI}/auth/oauth/authorize
            token-uri: ${HMPPS_AUTH_BASE_URI}/auth/oauth/token
            user-info-uri: ${HMPPS_MANAGE_USERS_BASE_URI}/users/me
            user-name-attribute: username
        registration:
          hmpps:
            client-id: ${HMPPS_AUTH_CLIENT_ID}
            client-secret: ${HMPPS_AUTH_CLIENT_SECRET}
            provider: hmpps
            scope: read
            authorization-grant-type: authorization_code
            redirect-uri: ${HMPPS_AUTH_REDIRECT_BASE_URI}/login/oauth2/code/hmpps

      resourceserver:
        jwt:
          issuer-uri: ${HMPPS_AUTH_BASE_URI}/auth/issuer

  flyway:
    locations: classpath:/db/migration/ddl,classpath:/db/migration/dml

resources:
  provider: s3
  endpoint.url: ${S3_ENDPOINT:}

import-files:
  locations: ${IMPORT_FILES_LOCATIONS}
  serco-prices: ${IMPORT_FILES_PRICES_SERCO}
  geo-prices: ${IMPORT_FILES_PRICES_GEO}

server:
  port: 8080
  servlet:
    session:
      cookie:
        secure: true
        max-age: 20M
        http-only: true
    context-path: /
  forward-headers-strategy: native
  tomcat:
    remoteip:
      remote-ip-header: x-forwarded-for
      protocol_header: x-forwarded-proto
  shutdown: graceful
  error:
    include-message: always

management:
  endpoints:
    web:
      base-path: /
      exposure:
        include: 'info, health'

  endpoint:
    health:
      cache:
        time-to-live: 2000ms
      show-components: always
      show-details: always
      probes:
        enabled: true
    info:
      cache:
        time-to-live: 2000ms
logging:
  level:
    ROOT: INFO
