resources:
  provider: s3
  endpoint.url: http://localhost:4572

server:
  shutdown: immediate

BASM_BUCKET_NAME:
  basm

JPC_BUCKET_NAME:
  jpc

import-files:
  locations: "schedule_34_locations_sample.xlsx"
  serco-prices: "serco_sample.xlsx"
  geo-prices: "geoamey_sample.xlsx"

export-files:
  template: classpath:/spreadsheets/JPC_template.xlsx

spring:
  security:
    oauth2:
      client:
        provider:
          hmpps:
            authorization-uri: http://localhost:9090/auth/oauth/authorize
#            authorization-uri: ${hmpps.auth.base.uri}/oauth/authorize
            token-uri: http://localhost:9090/auth/oauth/token
#            token-uri: ${hmpps.auth.base.uri}/oauth/token
            user-info-uri: http://localhost:9090/auth/api/user/me
#            user-info-uri: ${hmpps.auth.base.uri}/api/user/me
            user-name-attribute: name
        registration:
          hmpps:
            client-id: pecs-jpc-client
#            client-id: ${hmpps.auth.client.id}
            client-secret: clientsecret
#            client-secret: ${hmpps.auth.client.secret}
            provider: hmpps
            scope: read
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8080/login/oauth2/code/hmpps
#            redirect-uri: ${hmpps.auth.redirect.base.uri}/login/oauth2/code/hmpps
