# This cronjob works in conjunction with the 'daily-reports' profile defined within the application. By using this
# profile the application starts in non-web mode and the DailyReportsImporterRunner application runner class executes.
apiVersion: batch/v1
kind: CronJob
metadata:
  name: import-report-feed-placeholder
  namespace: calculate-journey-variable-payments-placeholder
spec:
  concurrencyPolicy: Forbid
  schedule: "3 6 * * *" # daily at 6:30 am UTC
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 2
  jobTemplate:
    spec:
      ttlSecondsAfterFinished: 100
      template:
        spec:
          containers:
            - name: import-report-feed-placeholder
              image: quay.io/hmpps/calculate-journey-variable-payments:latest
              imagePullPolicy: IfNotPresent
              resources:
                requests:
                  memory: 100Mi
                  cpu: 10m
                limits:
                  memory: 4096Mi
                  cpu: 2000m
              env:
                - name: SPRING_PROFILES_ACTIVE
                  value: "daily-reports"
                - name: JAVA_OPTS
                  value: "-Xmx3072m"
                - name: DB_HOST
                  valueFrom:
                    secretKeyRef:
                      name: rds-instance-calculate-journey-variable-payments-placeholder
                      key: database_host
                - name: DB_PORT
                  valueFrom:
                    secretKeyRef:
                      name: rds-instance-calculate-journey-variable-payments-placeholder
                      key: database_port
                - name: DB_NAME
                  valueFrom:
                    secretKeyRef:
                      name: rds-instance-calculate-journey-variable-payments-placeholder
                      key: database_name
                - name: DB_USERNAME
                  valueFrom:
                    secretKeyRef:
                      name: rds-instance-calculate-journey-variable-payments-placeholder
                      key: database_username
                - name: DB_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: rds-instance-calculate-journey-variable-payments-placeholder
                      key: database_password
                - name: APP_DB_URL
                  value: "jdbc:postgresql://$(DB_HOST):$(DB_PORT)/$(DB_NAME)?user=$(DB_USERNAME)&password=$(DB_PASSWORD)"
                - name: JPC_AWS_ACCESS_KEY_ID
                  valueFrom:
                    secretKeyRef:
                      name: calculate-journey-variable-payments-bucket
                      key: access_key_id
                - name: JPC_AWS_SECRET_ACCESS_KEY
                  valueFrom:
                    secretKeyRef:
                      name: calculate-journey-variable-payments-bucket
                      key: secret_access_key
                - name: JPC_BUCKET_NAME
                  valueFrom:
                    secretKeyRef:
                      name: calculate-journey-variable-payments-bucket
                      key: bucket_name
                - name: BASM_BUCKET_NAME
                  valueFrom:
                    secretKeyRef:
                      name: calculate-journey-variable-payments
                      key: BASM_BUCKET_NAME
                - name: BASM_AWS_ACCESS_KEY_ID
                  valueFrom:
                    secretKeyRef:
                      name: calculate-journey-variable-payments
                      key: BASM_AWS_ACCESS_KEY_ID
                - name: BASM_AWS_SECRET_ACCESS_KEY
                  valueFrom:
                    secretKeyRef:
                      name: calculate-journey-variable-payments
                      key: BASM_AWS_SECRET_ACCESS_KEY
                - name: HMPPS_AUTH_BASE_URI
                  value: "https://sign-in-placeholder.hmpps.service.justice.gov.uk/auth"
                - name: HMPPS_AUTH_REDIRECT_BASE_URI
                  value: "https://calculate-journey-variable-payments-placeholder.apps.live-1.cloud-platform.service.justice.gov.uk"
                - name: HMPPS_AUTH_CLIENT_ID
                  valueFrom:
                    secretKeyRef:
                      name: calculate-journey-variable-payments
                      key: HMPPS_AUTH_CLIENT_ID
                - name: HMPPS_AUTH_CLIENT_SECRET
                  valueFrom:
                    secretKeyRef:
                      name: calculate-journey-variable-payments
                      key: HMPPS_AUTH_CLIENT_SECRET
                - name: CRON_AUTOMATIC_LOCATION_MAPPING
                  value: "-"
                - name: CRON_IMPORT_REPORTS
                  value: "-"
                - name: CRON_BACKFILL_REPORTS
                  value: "-"
                - name: CRON_REPROCESS_EXISTING_MOVES
                  value: "-"
                - name: SENTRY_DSN
                  valueFrom:
                    secretKeyRef:
                      name: calculate-journey-variable-payments-sentry
                      key: sentry_dsn
                - name: SENTRY_ENVIRONMENT
                  value: "dev"
                - name: BASM_API_BASE_URL
                  value: "https://hmpps-book-secure-move-api-staging.apps.live-1.cloud-platform.service.justice.gov.uk"
                - name: FEEDBACK_URL
                  valueFrom:
                    secretKeyRef:
                      name: calculate-journey-variable-payments-feedback
                      key: feedback_url
                - name: FEATURE_FLAG_INCLUDE_RECONCILIATION_MOVES
                  value: "false"
                - name: IMPORT_REPORTS_BACKDATE_ENABLED
                  value: "true"
                - name: IMPORT_FILES_PRICES_GEO
                  value: "we_dont_care"
                - name: IMPORT_FILES_PRICES_SERCO
                  value: "we_dont_care"
                - name: IMPORT_FILES_LOCATIONS
                  value: "we_dont_care"
          restartPolicy: Never
