# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 2

image:
  repository: quay.io/hmpps/calculate-journey-variable-payments
  tag: latest
  port: 8080

db:
  secret_name: rds-instance-calculate-journey-variable-payments-preprod

sentry:
  secret_name: calculate-journey-variable-payments-sentry

feedback:
  secret_name: calculate-journey-variable-payments-feedback

ingress:
  enabled: true
  enable_whitelist: false
  hosts:
    - host: calculate-journey-variable-payments-preprod.apps.live-1.cloud-platform.service.justice.gov.uk
#      cert_secret: calculate-journey-variable-payments-cert
  path: /
  aws_weight: "100"

env:
  JAVA_OPTS: "-Xmx1024m"
  HMPPS_AUTH_BASE_URI: "https://sign-in-preprod.hmpps.service.justice.gov.uk/auth"
  HMPPS_AUTH_REDIRECT_BASE_URI: "https://calculate-journey-variable-payments-preprod.apps.live-1.cloud-platform.service.justice.gov.uk"
  CRON_AUTOMATIC_LOCATION_MAPPING: "0 30 3 * * ?"
  CRON_IMPORT_REPORTS: "0 30 5 * * ?"
  CRON_BACKFILL_REPORTS: "-"
  CRON_REPROCESS_EXISTING_MOVES: "0 0 10 22 MAR ?"
  SENTRY_ENVIRONMENT: preprod
  BASM_API_BASE_URL: "https://hmpps-book-secure-move-api-preprod.apps.live-1.cloud-platform.service.justice.gov.uk"

#whitelist:
#  office: "217.33.148.210/32"
#  health-kick: "35.177.252.195/32"
#  mojvpn: "81.134.202.29/32"
#  cloudplatform-live1-1: "35.178.209.113/32"
#  cloudplatform-live1-2: "3.8.51.207/32"
#  cloudplatform-live1-3: "35.177.252.54/32"
