# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 2

image:
  repository: quay.io/hmpps/calculate-journey-variable-payments
  tag: latest
  port: 8080

db:
  secret_name: rds-instance-calculate-journey-variable-payments-dev

sentry:
  secret_name: calculate-journey-variable-payments-sentry

feedback:
  secret_name: calculate-journey-variable-payments-feedback

ingress:
  enabled: true
  enable_whitelist: false
  hosts:
    - host: calculate-journey-variable-payments-dev.apps.live-1.cloud-platform.service.justice.gov.uk
#      cert_secret: calculate-journey-variable-payments-cert
  path: /
  aws_weight: "100"

env:
  JAVA_OPTS: "-Xmx1024m"
  HMPPS_AUTH_BASE_URI: "https://sign-in-dev.hmpps.service.justice.gov.uk/auth"
  HMPPS_AUTH_REDIRECT_BASE_URI: "https://calculate-journey-variable-payments-dev.apps.live-1.cloud-platform.service.justice.gov.uk"
  CRON_AUTOMATIC_LOCATION_MAPPING: "0 30 13 * * ?"
  CRON_IMPORT_REPORTS: "0 30 5 * * ?"
  CRON_BACKFILL_REPORTS: "-"
  SENTRY_ENVIRONMENT: dev
  BASM_API_BASE_URL: "https://hmpps-book-secure-move-api-staging.apps.live-1.cloud-platform.service.justice.gov.uk"
