# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 2

image:
  repository: quay.io/hmpps/calculate-journey-variable-payments
  tag: latest
  port: 8080

db:
  secret_name: rds-instance-calculate-journey-variable-payments-dev

ingress:
  enabled: true
  enable_whitelist: false
  hosts:
    - host: calculate-journey-variable-payments-dev.apps.live-1.cloud-platform.service.justice.gov.uk
#      cert_secret: calculate-journey-variable-payments-cert
  path: /

env:
  JAVA_OPTS: "-Xmx2048m"
  HMPPS_AUTH_BASE_URI: "https://sign-in-dev.hmpps.service.justice.gov.uk/auth"
  HMPPS_AUTH_REDIRECT_BASE_URI: "https://calculate-journey-variable-payments-dev.apps.live-1.cloud-platform.service.justice.gov.uk"
  CRON_IMPORT_REPORTS: "0 0 14 * * ?"